# Stellar.toml

VERSION="2.0"

[DOCUMENTATION]
ORG_NAME="BGL Token"
ORG_URL="https://bestgoldliquidity.art"
ORG_DESCRIPTION="Official token for safe transactions"
ORG_EMAIL="support@bestgoldliquidity.art"

[[CURRENCIES]]
code="BGL"
issuer="GCT7OQYILG5QPWGTDW4YIZNFRRGSVSXFF7HMI3A5UDBWID2DB5DC6SOX"
status="active"
display_decimals=2
name="BGL Token"
desc="BGL - it is a token for internal settlements and decentralized operations."
image="https://i.imgur.com/IMA9CwF.png"
